---
title: "writing_functions"
output: github_document
date: "2022-10-29"
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(ggplot2)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Simulations

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

How did we use this before?

```{r}
sim_mean_sd(n = 30)
```


How can we use this now?

Let's start with a for loop

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  output[[i]] = sim_mean_sd(n = 30)
}

bind_rows(output)
```
Let's use list columns instead

```{r}
sim_results_df = 
  expand_grid(
    sample_size = 30,
    iteration = 1:100
  ) %>% #give all possible combinations of this sample size and this iteration
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>%
  unnest(estimate_df)
```

```{r}
sim_results_df %>%
  ggplot(aes(x = mu_hat)) +
  geom_density()
```


## what about changing sample size

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 120, 240),
    iteration = 1:100
  ) %>% #give all possible combinations of this sample size and this iteration
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>%
  unnest(estimate_df)
```

```{r}
sim_results_df %>%
  mutate(
    sample_size = str_c("N = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% # violin need x to be factor not number
  ggplot(aes(x = sample_size, y = mu_hat)) +
  geom_violin()
```

```{r}
sim_results_df %>%
  mutate(
    sample_size = str_c("N = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  group_by(sample_size) %>%
  summarize(
    em_st_err = sd(mu_hat)
  )
```


## Let's see two inputs

```{r, cache=TRUE}
#cache=TRUE saves the result, don't rerun as long as code unchange
#if this code chunk depends on other code chunk, changing the other code chunk doesn not cause this code chunk to rerun, which can cause problems
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 120, 240),
    true_sigma = c(6, 3),
    iteration = 1:1000
  ) %>% #give all possible combinations of this sample size and this iteration
  mutate(
    estimate_df = map2(.x = sample_size, .y = true_sigma, ~sim_mean_sd(n = .x, sigma = .y))
  ) %>% #map2 lets sim_mean_sd take two inputs, need to name inputs explicitly
  unnest(estimate_df)
```


```{r}
sim_results_df %>%
  mutate(
    sample_size = str_c("N = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% # violin need x to be factor not number
  ggplot(aes(x = sample_size, y = mu_hat)) +
  geom_violin() + 
  facet_grid(. ~true_sigma)
```

